services:
  brain-api:
    image: ghissari/wireguard-brain:latest
    container_name: wireguard-brain-api
    restart: unless-stopped
    ports:
      - "13121:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
